### ISSUE TITLE
失败几率有点高哦，难得成功几次

### ISSUE THREAD

**Issue by jy02534655** [xtaw/LiteLoaderQQNT-Daily-Card#1]
如题

**Comment by xtaw** [comment]
请给出错误信息

**Comment by jy02534655** [comment]
![image](https://github.com/xtaw/LiteLoaderQQNT-Daily-Card/assets/4277777/d5ee91d0-c854-422c-a63f-ad6f32843e8e)
经常是这个错误 错误信息:Failed to draw lucky card. Details: [backend]no claim card count

**Comment by xtaw** [comment]
这个错误是没有抽取次数了，不知道为什么总是会少一次，你可以从手机上看，的确是没有次数的

**Comment by jy02534655** [comment]
好吧，手机能用插件么？没搞过
